version: '3.8'

services:
  Jenkins-builder:
    image: linuxserver/jenkins-builder:latest
    container_name: Jenkins-builder
    restart: unless-stopped
    ports:
      - "80:80/tcp"
    volumes:
      - /volume1/docker/jenkins-builder/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
