version: '3.8'

services:
  Chowdown:
    image: gregyankovoy/chowdown:latest
    container_name: Chowdown
    restart: unless-stopped
    ports:
      - "4000:4000/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Chowdown:/config
