version: '3.8'

services:
  nord-vpn:
    image: azinchen/nordvpn:latest
    container_name: nord-vpn
    restart: unless-stopped
    ports:
      - "8080:80/tcp"
    environment:
      USER: user@email.com
      PASS: password
      COUNTRY: Spain;Hong Kong;IE;131
      GROUP: Standard VPN servers
      RANDOM_TOP: 10
      RECREATE_VPN_CRON: 5 */3 * * *
      CHECK_CONNECTION_URL: "https://www.google.com"
      NETWORK: 192.168.1.0/24;192.168.2.0/24
      OPENVPN_OPTS: --mute-replay-warnings
