version: '3.8'

services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    container_name: unifi-controller
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080/tcp"
      - "8081:8081/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
      - "8880:8880/tcp"
      - "6789:6789/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Unifi:/config
    environment:
      PUID: 1000
      PGID: 100
