version: '3.8'

services:
  Pairdrop:
    image: linuxserver/pairdrop:latest
    container_name: Pairdrop
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    volumes:
      - /volume1/docker/pairdrop/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      RATE_LIMIT: false
      WS_FALLBACK: false
      RTC_CONFIG: ${RTC_CONFIG}
      DEBUG_MODE: false
