version: '3.8'

services:
  Ngircd:
    image: linuxserver/ngircd:latest
    container_name: Ngircd
    restart: unless-stopped
    ports:
      - "6667:6667/tcp"
    volumes:
      - /volume1/docker/ngircd/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
