version: '3.8'

services:
  pihole-unbound:
    image: cbcrowe/pihole-unbound:latest
    container_name: pihole-unbound
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "1010:80/tcp"
      - "4443:443/tcp"
    volumes:
      - /portainer/Files/AppData/Config/PiHole-Unbound:/etc/pihole
      - /portainer/Files/AppData/Config/PiHole-Unbound/DNS:/etc/dnsmasq.d
    environment:
      ServerIP: 192.168.0.X
      TZ: Europe\London
      DNSSEC: ${DNSSEC}
      DNS1: "127.0.0.1#5335"
      DNS2: "127.0.0.1#5335"
