version: '3.8'

services:
  pureftp:
    image: stilliard/pure-ftpd:hardened
    container_name: pureftp
    restart: unless-stopped
    ports:
      - "21/tcp"
      - "30000/tcp"
      - "30001/tcp"
      - "30002/tcp"
      - "30003/tcp"
      - "30004/tcp"
      - "30005/tcp"
      - "30006/tcp"
      - "30007/tcp"
      - "30008/tcp"
      - "30009/tcp"
    volumes:
      - /opt/mediadepot/apps/pureftp:/etc/pure-ftpd/passwd
      - /media/storage/tvshows:/data/tvshows
      - /media/storage/movies:/data/movies
      - /media/storage/music:/data/music
      - /media/storage/ebooks:/data/ebooks
      - /media/storage/photos:/data/photos
      - /media/storage/documents:/data/documents
      - /media/storage/downloads:/data/downloads
      - /media/storage/software:/data/software
      - /media/temp/blackhole:/data/blackhole
      - /media/temp/processing:/data/processing
    environment:
      FTP_USER_NAME: depot
      FTP_USER_PASS: badpass
      FTP_USER_HOME: /data
      FTP_USER_GID: 15000
      FTP_USER_UID: 15000
      TZ: America/Los_Angeles
      PUBLICHOST: localhost
