version: '3.8'

services:
  scrutiny:
    image: analogj/scrutiny:latest
    container_name: scrutiny
    restart: unless-stopped
    ports:
      - "8080/tcp"
    volumes:
      - /opt/mediadepot/apps/scrutiny:/scrutiny/config/
      - /run/udev:/run/udev
    labels:
      traefik.enable: "true"
      traefik.http.services.scrutiny.loadbalancer.server.port: "8080"
      traefik.http.routers.scrutiny.entrypoints: "websecure"
      traefik.http.routers.scrutiny.tls.certresolver: "mydnschallenge"
