version: '3.8'

services:
  gophish:
    image: gophish/gophish:latest
    container_name: gophish
    restart: unless-stopped
    ports:
      - "3333:3333/tcp"
    environment:
      PUID: 1000
      PGID: 100
