version: '3.8'

services:
  Ardour:
    image: linuxserver/ardour:latest
    container_name: Ardour
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/ardour/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      SUBFOLDER: /
