version: '3.8'

services:
  Pydio-cells:
    image: linuxserver/pydio-cells:latest
    container_name: Pydio-cells
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - /volume1/docker/pydio-cells/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      EXTERNALURL: yourdomain.url
      SERVER_IP: 0.0.0.0
