version: '3.8'

services:
  Orcaslicer:
    image: linuxserver/orcaslicer:latest
    container_name: Orcaslicer
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/orcaslicer/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
