version: '3.8'

services:
  Grav:
    image: linuxserver/grav:latest
    container_name: Grav
    restart: unless-stopped
    ports:
      - "80:80/tcp"
    volumes:
      - /volume1/docker/grav/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
