version: '3.8'

services:
  unmanic:
    image: josh5/unmanic:latest
    container_name: unmanic
    restart: unless-stopped
    ports:
      - "8888:8888/tcp"
    volumes:
      - /portainer/Files/AppData/Config/unmanic/config:/config
      - /portainer/Files/AppData/Config/unmanic/library:/library
      - /portainer/Files/AppData/Config/unmanic/tmp:/tmp/unmanic
    environment:
      PUID: 1000
      PGID: 1000
