version: '3.8'

services:
  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    ports:
      - "2368:2368/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Ghost:/var/lib/ghost/content
    environment:
      NODE_ENV: development
      url: "http://localhost/"
