version: '3.8'

services:
  pixel-server:
    image: macley/pixel-server:latest
    container_name: pixel-server
    restart: unless-stopped
    ports:
      - "85:80/tcp"
    volumes:
      - /portainer/Files/AppData/Config/pixel-server/auth.cfg:/opt/pixel-server/auth.cfg
      - /portainer/Files/AppData/Config/pixel-server/pixelserver.cfg:/opt/pixel-server/pixelserver.cfg
      - /portainer/Files/AppData/Config/pixel-server/users.cfg:/opt/pixel-server/users.cfg
      - undefined:/etc/crontabs/
