version: '3.8'

services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    ports:
      - "5055/tcp"
    volumes:
      - /opt/mediadepot/apps/overseerr:/config
      - /etc/localtime:/etc/localtime
    environment:
      PGID: 15000
      PUID: 15000
      TZ: America/Los_Angeles
    labels:
      traefik.enable: "true"
      traefik.http.services.overseerr.loadbalancer.server.port: "5055"
      traefik.http.routers.overseerr.entrypoints: "websecure"
      traefik.http.routers.overseerr.tls.certresolver: "mydnschallenge"
