version: '3.8'

services:
  Snibox:
    image: snowmean/snibox-sqlite:latest
    container_name: Snibox
    restart: unless-stopped
    ports:
      - "3010:3000/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Snibox:/app/db/database
