version: '3.8'

services:
  Shotcut:
    image: linuxserver/shotcut:latest
    container_name: Shotcut
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/shotcut/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
