version: '3.8'

services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    ports:
      - "8083:8083/tcp"
    volumes:
      - /portainer/Books:/books
      - /portainer/Files/AppData/Config/Calibre-web:/config
    environment:
      PUID: 1000
      PGID: 100
