version: '3.8'

services:
  couchpotato:
    image: linuxserver/couchpotato:latest
    container_name: couchpotato
    restart: unless-stopped
    ports:
      - "5050/tcp"
    volumes:
      - /opt/mediadepot/apps/couchpotato:/config
      - /media/storage/downloads/movies:/downloads
      - /media/storage/movies:/movies
      - /media/temp/blackhole/movies:/blackhole
    environment:
      PGID: 15000
      PUID: 15000
      TZ: America/Los_Angeles
    labels:
      traefik.enable: "true"
      traefik.http.services.couchpotato.loadbalancer.server.port: "5050"
      traefik.http.routers.couchpotato.entrypoints: "websecure"
      traefik.http.routers.couchpotato.tls.certresolver: "mydnschallenge"
