version: '3.8'

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    volumes:
      - /opt/mediadepot/apps/plex:/config
      - /media/storage/tvshows:/data/tvshows
      - /media/storage/movies:/data/movies
      - /media/storage/music:/data/music
      - undefined:/transcode
    environment:
      PGID: 15000
      PUID: 15000
      TZ: America/Los_Angeles
      VERSION: latest
    labels:
      traefik.enable: "true"
      traefik.http.services.plex.loadbalancer.server.port: "32400"
