version: '3.8'

services:
  Gitqlient:
    image: linuxserver/gitqlient:latest
    container_name: Gitqlient
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/gitqlient/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
