version: '3.8'

services:
  Cura:
    image: linuxserver/cura:latest
    container_name: Cura
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/cura/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
