version: '3.8'

services:
  Mysql-workbench:
    image: linuxserver/mysql-workbench:latest
    container_name: Mysql-workbench
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/mysql-workbench/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
