version: '3.8'

services:
  Planka:
    image: linuxserver/planka:latest
    container_name: Planka
    restart: unless-stopped
    ports:
      - "1337:1337/tcp"
    volumes:
      - /volume1/docker/planka/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      BASE_URL: "https://planka.example.com"
      DATABASE_URL: "postgresql://user:password@planka-db:5432/planka"
      DEFAULT_ADMIN_EMAIL: demo@demo.demo
      DEFAULT_ADMIN_USERNAME: demo
      DEFAULT_ADMIN_PASSWORD: demo
      DEFAULT_ADMIN_NAME: Demo User
      SECRET_KEY: notasecretkey
      TRUST_PROXY: 0
