version: '3.8'

services:
  Kicad:
    image: linuxserver/kicad:latest
    container_name: Kicad
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/kicad/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
