version: '3.8'

services:
  omada-controller:
    image: mbentley/omada-controller:latest
    container_name: omada-controller
    restart: unless-stopped
    ports:
      - "8088:8088/tcp"
      - "8043:8043/tcp"
      - "27001:27001/udp"
      - "27002:27002/tcp"
      - "29810:29810/udp"
      - "29811:29811/tcp"
      - "29812:29812/tcp"
      - "29813:29813/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Omada:/config
    environment:
      PUID: 1000
      PGID: 1000
