version: '3.8'

services:
  Adguardhome:
    image: adguard/adguardhome:latest
    container_name: Adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3001:3000/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - /portainer/Files/AppData/Config/AdguardHome/config:/opt/adguardhome/conf
      - /portainer/Files/AppData/Config/AdguardHome/work:/opt/adguardhome/work
