version: '3.8'

services:
  JDownloader:
    image: jaymoulin/jdownloader:latest
    container_name: JDownloader
    restart: unless-stopped
    ports:
      - "3129:3129/tcp"
    volumes:
      - /portainer/Files/AppData/Config/JDownloader:/opt/JDownloader/app/cfg
      - /portainer/Downloads:/opt/JDownloader/Downloads
    environment:
      MYJD_DEVICE_NAME: ${MYJD_DEVICE_NAME}
      MYJD_USER: ${MYJD_USER}
      MYJD_PASSWORD: ${MYJD_PASSWORD}
