version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      AUTH_KEY: ${AUTH_KEY}
