version: '3.8'

services:
  shiori:
    image: radhifadlillah/shiori:latest
    container_name: shiori
    restart: unless-stopped
    ports:
      - "8080/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Shiori:/srv/shiori
