version: '3.8'

services:
  Python:
    image: linuxserver/python:latest
    container_name: Python
    restart: unless-stopped
    ports:
      - "80:80/tcp"
    volumes:
      - /volume1/docker/python/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
