version: '3.8'

services:
  immich:
    image: undefined
    container_name: immich
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      IMMICH_VERSION: release
      DB_USERNAME: postgres
      DB_PASSWORD: please-change-this-to-a-random-secret
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich_postgres
      UPLOAD_LOCATION: /portainer/Files/AppData/Immich/upload
      REDIS_HOSTNAME: immich_redis
      PORT: 2283
