version: '3.8'

services:
  Fleet:
    image: linuxserver/fleet:latest
    container_name: Fleet
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - /volume1/docker/fleet/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      fleet_admin_authentication_type: DATABASE
      fleet_database_url: "jdbc:mariadb://<url>:3306/fleet"
      fleet_database_username: fleet_user
      fleet_database_password: dbuserpassword
      fleet_admin_secret: randomstring
