version: '3.8'

services:
  Webcord:
    image: linuxserver/webcord:latest
    container_name: Webcord
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/webcord/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
