version: '3.8'

services:
  beets:
    image: linuxserver/beets:latest
    container_name: beets
    restart: unless-stopped
    ports:
      - "8337:8337/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Beets:/config
      - /portainer/Downloads:/downloads
      - /portainer/Music:/music
    environment:
      PUID: 1000
      PGID: 100
