version: '3.8'

services:
  airsonic:
    image: linuxserver/airsonic:latest
    container_name: airsonic
    restart: unless-stopped
    ports:
      - "4040:4040/tcp"
    volumes:
      - /portainer/Music:/music
      - /portainer/Files/AppData/Airsonic/Playlists:/playlists
      - /portainer/Podcasts:/podcasts
      - /portainer/Files/AppData/Airsonic/Media:/media
      - /portainer/Files/AppData/Config/Airsonic/:/config
    environment:
      PUID: 1000
      PGID: 100
      CONTEXT_PATH: ${CONTEXT_PATH}
      JAVA_OPTS: ${JAVA_OPTS}
