version: '3.8'

services:
  Series-troxide:
    image: linuxserver/series-troxide:latest
    container_name: Series-troxide
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/series-troxide/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
