version: '3.8'

services:
  influxdb1810:
    image: influxdb:1.8.10
    container_name: influxdb1810
    restart: unless-stopped
    ports:
      - "8086:8086/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Influxdb/data:/var/lib/influxdb
      - /portainer/Files/AppData/Config/Influxdb/config:/etc/influxdb
