version: '3.8'

services:
  chrony-ntp:
    image: cturra/ntp:latest
    container_name: chrony-ntp
    restart: unless-stopped
    ports:
      - "123:123/udp"
    environment:
      LOG_LEVEL: 0
      NTP_SERVERS: time.cloudflare.com
