version: '3.8'

services:
  Calibre:
    image: linuxserver/calibre:latest
    container_name: Calibre
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
      - "8081:8081/tcp"
    volumes:
      - /volume1/docker/calibre/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      PASSWORD: ${PASSWORD}
      CLI_ARGS: ${CLI_ARGS}
