version: '3.8'

services:
  nginx-proxy-manager-sqlite:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager-sqlite
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "81:81/tcp"
      - "443:443/tcp"
    volumes:
      - /portainer/Files/AppData/Config/nginx-proxy-manager/data:/data
      - /portainer/Files/AppData/Config/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
