version: '3.8'

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    restart: unless-stopped
    ports:
      - "5000/tcp"
    volumes:
      - /opt/mediadepot/apps/changedetection:/datastore
    labels:
      traefik.enable: "true"
      traefik.http.services.changedetection.loadbalancer.server.port: "5000"
      traefik.http.routers.changedetection.entrypoints: "websecure"
      traefik.http.routers.changedetection.tls.certresolver: "mydnschallenge"
