version: '3.8'

services:
  AriaNG:
    image: hurlenko/aria2-ariang:latest
    container_name: AriaNG
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - /portainer/Files/AppData/Config/AriaNG:/aria2/conf
      - /portainer/Downloads:/aria2/data
    environment:
      PUID: 1000
      PGID: 1000
      ARIA2RPCPORT: 443
