version: '3.8'

services:
  Github-desktop:
    image: linuxserver/github-desktop:latest
    container_name: Github-desktop
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/github-desktop/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
