version: '3.8'

services:
  Snapdrop:
    image: linuxserver/snapdrop:latest
    container_name: Snapdrop
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /volume1/docker/snapdrop/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
