version: '3.8'

services:
  Sqlitebrowser:
    image: linuxserver/sqlitebrowser:latest
    container_name: Sqlitebrowser
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/sqlitebrowser/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
