version: '3.8'

services:
  Firefox:
    image: linuxserver/firefox:latest
    container_name: Firefox
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    volumes:
      - /volume1/docker/firefox/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
