version: '3.8'

services:
  homebridge-debian:
    image: homebridge/homebridge:ubuntu-arm32v7
    container_name: homebridge-debian
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/debian-homebridge:/homebridge
    environment:
      PGID: 1000
      PUID: 1000
      HOMEBRIDGE_CONFIG_UI: 1
      HOMEBRIDGE_CONFIG_UI_PORT: 8581
      TZ: America/New_York
