version: '3.8'

services:
  yacht:
    image: selfhostedpro/yacht:latest
    container_name: yacht
    restart: unless-stopped
    ports:
      - "8001:8000/tcp"
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
