version: '3.8'

services:
  Qemu-static:
    image: linuxserver/qemu-static:latest
    container_name: Qemu-static
    restart: unless-stopped
    ports:
      - "80:80/tcp"
    volumes:
      - /volume1/docker/qemu-static/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
