version: '3.8'

services:
  statping:
    image: statping/statping:latest
    container_name: statping
    restart: unless-stopped
    ports:
      - "4040:8080/tcp"
    volumes:
      - /portainer/Files/AppData/Config/statping:/app
