version: '3.8'

services:
  Mediaelch:
    image: linuxserver/mediaelch:latest
    container_name: Mediaelch
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/mediaelch/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
