version: '3.8'

services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn
    restart: unless-stopped
    ports:
      - "9091:9091/tcp"
    volumes:
      - /portainer/Downloads:/data
      - /etc/localtime:/etc/localtime
    environment:
      PUID: 1000
      PGID: 100
      OPENVPN_PROVIDER: MULLVAD
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      LOCAL_NETWORK: 192.168.0.0/24
