version: '3.8'

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Jellyfin:/config
      - /portainer/TV:/data/tvshows
      - /portainer/Movies:/data/movies
    environment:
      PUID: 1000
      PGID: 100
      TZ: ${TZ}
