version: '3.8'

services:
  Steamos:
    image: linuxserver/steamos:latest
    container_name: Steamos
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
      - "27031-27036:27031-27036/udp"
      - "27031-27036:27031-27036"
      - "47984-47990:47984-47990"
      - "48010-48010:48010-48010"
      - "47998-48000:47998-48000/udp"
    volumes:
      - /volume1/docker/steamos/config:/config
      - /dev/input:/dev/input
      - /run/udev/data:/run/udev/data
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      DRINODE: /dev/dri/renderD128
      HOST_IP: 192.168.100.10
      STARTUP: KDE
      RESOLUTION: 1920x1080
