version: '3.8'

services:
  Swag:
    image: linuxserver/swag:latest
    container_name: Swag
    restart: unless-stopped
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    volumes:
      - /volume1/docker/swag/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      URL: yourdomain.url
      VALIDATION: http
      SUBDOMAINS: www,
      CERTPROVIDER: ${CERTPROVIDER}
      DNSPLUGIN: cloudflare
      PROPAGATION: ${PROPAGATION}
      EMAIL: ${EMAIL}
      ONLY_SUBDOMAINS: false
      EXTRA_DOMAINS: ${EXTRA_DOMAINS}
      STAGING: false
