version: '3.8'

services:
  rclone:
    image: mediadepot/rclone:latest
    container_name: rclone
    restart: unless-stopped
    volumes:
      - /opt/mediadepot/apps/rclone:/srv/rclone/config
      - /opt/mediadepot/apps:/mnt/data
