version: '3.8'

services:
  Audacity:
    image: linuxserver/audacity:latest
    container_name: Audacity
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    volumes:
      - /volume1/docker/audacity/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
