version: '3.8'

services:
  Netbox:
    image: linuxserver/netbox:latest
    container_name: Netbox
    restart: unless-stopped
    ports:
      - "8000:8000/tcp"
    volumes:
      - /volume1/docker/netbox/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      SUPERUSER_EMAIL: <SUPERUSER_EMAIL>
      SUPERUSER_PASSWORD: <SUPERUSER_PASSWORD>
      ALLOWED_HOST: <ALLOWED_HOST>
      DB_NAME: <DB_NAME>
      DB_USER: <DB_USER>
      DB_PASSWORD: <DB_PASSWORD>
      DB_HOST: <DB_HOST>
      DB_PORT: <DB_PORT>
      REDIS_HOST: <REDIS_HOST>
      REDIS_PORT: <REDIS_PORT>
      REDIS_PASSWORD: <REDIS_PASSWORD>
      REDIS_DB_TASK: <REDIS_DB_TASK>
      REDIS_DB_CACHE: <REDIS_DB_CACHE>
      BASE_PATH: <BASE_PATH>
      REMOTE_AUTH_ENABLED: <REMOTE_AUTH_ENABLED>
      REMOTE_AUTH_BACKEND: <REMOTE_AUTH_BACKEND>
      REMOTE_AUTH_HEADER: <REMOTE_AUTH_HEADER>
      REMOTE_AUTH_AUTO_CREATE_USER: <REMOTE_AUTH_AUTO_CREATE_USER>
      REMOTE_AUTH_DEFAULT_GROUPS: <REMOTE_AUTH_DEFAULT_GROUPS>
      REMOTE_AUTH_DEFAULT_PERMISSIONS: <REMOTE_AUTH_DEFAULT_PERMISSIONS>
