version: '3.8'

services:
  Readme-sync:
    image: linuxserver/readme-sync:latest
    container_name: Readme-sync
    restart: unless-stopped
    ports:
      - "80:80/tcp"
    volumes:
      - /volume1/docker/readme-sync/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
