version: '3.8'

services:
  homarr-secured:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr-secured
    restart: unless-stopped
    ports:
      - "7575:7575/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Homarr/configs:/app/data/configs
      - /portainer/Files/AppData/Config/Homarr/icons:/app/public/icons
    environment:
      PUID: 1000
      PGID: 1000
