version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "81:81/tcp"
      - "443:443/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Nginx-Proxy/data:/data
      - /portainer/Files/AppData/Config/Nginx-Proxy/letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: /data/database.sqlite
