version: '3.8'

services:
  Digikam:
    image: linuxserver/digikam:latest
    container_name: Digikam
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/digikam/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      SUBFOLDER: /
