version: '3.8'

services:
  bitwardenrs:
    image: bitwardenrs/server:latest
    container_name: bitwardenrs
    restart: unless-stopped
    ports:
      - "80/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Bitwarden-rs:/config
