version: '3.8'

services:
  thelounge:
    image: linuxserver/thelounge:latest
    container_name: thelounge
    restart: unless-stopped
    ports:
      - "9000:9000/tcp"
    volumes:
      - /portainer/Files/AppData/Config/TheLounge:/config
    environment:
      PUID: 1000
      PGID: 100
