version: '3.8'

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    ports:
      - "8902:8080/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Homer/assets:/www/assets
      - /portainer/Files/AppData/Config/Homer:/www/config.yml
