version: '3.8'

services:
  infisical:
    image: undefined
    container_name: infisical
    restart: unless-stopped
    environment:
      PORT: 8078
      ENCRYPTION_KEY: c6606cd2daad581c4de96531427aae0d
      AUTH_SECRET: 5lrMXKKWCVocS/uerPsl7V+TX/aaUaI7iDkgl3tSmLE=
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: infisical
      POSTGRES_DB: infisical
      DB_CONNECTION_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      SITE_URL: "http://localhost:8078"
      REDIS_URL: "redis://redis:6379"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_NAME: ${SMTP_NAME}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      CLIENT_ID_HEROKU: ${CLIENT_ID_HEROKU}
      CLIENT_SECRET_HEROKU: ${CLIENT_SECRET_HEROKU}
      CLIENT_ID_VERCEL: ${CLIENT_ID_VERCEL}
      CLIENT_SECRET_VERCEL: ${CLIENT_SECRET_VERCEL}
      CLIENT_SLUG_VERCEL: ${CLIENT_SLUG_VERCEL}
      CLIENT_ID_NETLIFY: ${CLIENT_ID_NETLIFY}
      CLIENT_SECRET_NETLIFY: ${CLIENT_SECRET_NETLIFY}
      CLIENT_ID_GITHUB: ${CLIENT_ID_GITHUB}
      CLIENT_SECRET_GITHUB: ${CLIENT_SECRET_GITHUB}
      CLIENT_ID_GITLAB: ${CLIENT_ID_GITLAB}
      CLIENT_SECRET_GITLAB: ${CLIENT_SECRET_GITLAB}
      CLIENT_ID_BITBUCKET: ${CLIENT_ID_BITBUCKET}
      CLIENT_SECRET_BITBUCKET: ${CLIENT_SECRET_BITBUCKET}
      SENTRY_DSN: ${SENTRY_DSN}
      CLIENT_ID_GOOGLE_LOGIN: ${CLIENT_ID_GOOGLE_LOGIN}
      CLIENT_SECRET_GOOGLE_LOGIN: ${CLIENT_SECRET_GOOGLE_LOGIN}
      CLIENT_ID_GITHUB_LOGIN: ${CLIENT_ID_GITHUB_LOGIN}
      CLIENT_SECRET_GITHUB_LOGIN: ${CLIENT_SECRET_GITHUB_LOGIN}
      CLIENT_ID_GITLAB_LOGIN: ${CLIENT_ID_GITLAB_LOGIN}
      CLIENT_SECRET_GITLAB_LOGIN: ${CLIENT_SECRET_GITLAB_LOGIN}
      CAPTCHA_SECRET: ${CAPTCHA_SECRET}
      NEXT_PUBLIC_CAPTCHA_SITE_KEY: ${NEXT_PUBLIC_CAPTCHA_SITE_KEY}
      PLAIN_API_KEY: ${PLAIN_API_KEY}
      PLAIN_WISH_LABEL_IDS: ${PLAIN_WISH_LABEL_IDS}
