version: '3.8'

services:
  quassel-core:
    image: linuxserver/quassel-core:latest
    container_name: quassel-core
    restart: unless-stopped
    ports:
      - "4242:4242/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Quassel-core:/config
    environment:
      PUID: 1000
      PGID: 100
