version: '3.8'

services:
  syncserver:
    image: mozilla/syncserver:latest
    container_name: syncserver
    restart: unless-stopped
    ports:
      - "5000/tcp"
    volumes:
      - /opt/mediadepot/apps/syncserver:/data
    environment:
      SYNCSERVER_PUBLIC_URL: "https://syncserver.depot.lan"
      SYNCSERVER_SECRET_FILE: /data/secret_key
      SYNCSERVER_SQLURI: "sqlite:////data/syncserver.db"
      SYNCSERVER_BATCH_UPLOAD_ENABLED: true
      SYNCSERVER_FORCE_WSGI_ENVIRON: false
      PORT: 5000
    labels:
      traefik.enable: "true"
      traefik.http.services.syncservere.loadbalancer.server.port: "5000"
      traefik.http.routers.syncserver.entrypoints: "websecure"
      traefik.http.routers.syncserver.tls.certresolver: "mydnschallenge"
