version: '3.8'

services:
  Wireguard:
    image: linuxserver/wireguard:latest
    container_name: Wireguard
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
    volumes:
      - /volume1/docker/wireguard/config:/config
      - /lib/modules:/lib/modules
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      SERVERURL: wireguard.domain.com
      SERVERPORT: 51820
      PEERS: 1
      PEERDNS: auto
      INTERNAL_SUBNET: 10.13.13.0
      ALLOWEDIPS: 0.0.0.0/0
