version: '3.8'

services:
  Opera:
    image: linuxserver/opera:latest
    container_name: Opera
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/opera/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      OPERA_CLI: "https://www.linuxserver.io/"
