version: '3.8'

services:
  Freetube:
    image: linuxserver/freetube:latest
    container_name: Freetube
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/freetube/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
