version: '3.8'

services:
  ubooquity:
    image: linuxserver/ubooquity:latest
    container_name: ubooquity
    restart: unless-stopped
    ports:
      - "2202:2202/tcp"
      - "2203:2203/tcp"
    volumes:
      - undefined:/books
      - undefined:/comics
      - undefined:/config
    environment:
      MAXMEM: ${MAXMEM}
      PUID: 1000
      PGID: 100
