version: '3.8'

services:
  Keepassxc:
    image: linuxserver/keepassxc:latest
    container_name: Keepassxc
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/keepassxc/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
