version: '3.8'

services:
  Foldingathome:
    image: linuxserver/foldingathome:latest
    container_name: Foldingathome
    restart: unless-stopped
    ports:
      - "7396:7396/tcp"
      - "36330:36330/tcp"
    volumes:
      - /volume1/docker/foldingathome/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
