version: '3.8'

services:
  EmbyStat:
    image: linuxserver/embystat:latest
    container_name: EmbyStat
    restart: unless-stopped
    ports:
      - "6555:6555/tcp"
    volumes:
      - /portainer/Files/AppData/Config/EmbyStat:/config
