version: '3.8'

services:
  Changedetection.io:
    image: linuxserver/changedetection.io:latest
    container_name: Changedetection.io
    restart: unless-stopped
    ports:
      - "5000:5000/tcp"
    volumes:
      - /volume1/docker/changedetection.io/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      BASE_URL: ${BASE_URL}
      PLAYWRIGHT_DRIVER_URL: ${PLAYWRIGHT_DRIVER_URL}
