version: '3.8'

services:
  Mylar3:
    image: linuxserver/mylar3:latest
    container_name: Mylar3
    restart: unless-stopped
    ports:
      - "8090:8090/tcp"
    volumes:
      - /volume1/docker/mylar3/config:/config
      - /volume1/docker/mylar3/comics:/comics
      - /volume1/docker/mylar3/downloads:/downloads
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
