version: '3.8'

services:
  huginn:
    image: huginn/huginn:latest
    container_name: huginn
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    volumes:
      - /portainer/Files/AppData/Config/huginn:/var/lib/mysql
