version: '3.8'

services:
  Obsidian:
    image: linuxserver/obsidian:latest
    container_name: Obsidian
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/obsidian/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
