version: '3.8'

services:
  octoprint:
    image: octoprint/octoprint:latest
    container_name: octoprint
    restart: unless-stopped
    ports:
      - "8051:80/tcp"
    volumes:
      - /portainer/Files/AppData/Config/OctoPrint:/octoprint
      - /dev:/dev
    environment:
      NODE_ENV: development 
      ENABLE_MJPG_STREAMER: true
