version: '3.8'

services:
  domoticz:
    image: linuxserver/domoticz:latest
    container_name: domoticz
    restart: unless-stopped
    ports:
      - "1443:1443/tcp"
      - "6144:6144/tcp"
      - "8080:8080/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Domoticz:/config
    environment:
      PUID: 1000
      PGID: 100
