version: '3.8'

services:
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    ports:
      - "6789:6789/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Nzbget:/config
      - /portainer/Downloads:/downloads
    environment:
      PUID: 1000
      PGID: 100
