version: '3.8'

services:
  Krita:
    image: linuxserver/krita:latest
    container_name: Krita
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/krita/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
