version: '3.8'

services:
  gotify:
    image: gotify/server-arm7:latest
    container_name: gotify
    restart: unless-stopped
    ports:
      - "9008:80/tcp"
    volumes:
      - /portainer/Files/AppData/Config/gotify:/app/data
    environment:
      TZ: America/New_York
      GOTIFY_DEFAULTUSER_NAME: admin
      GOTIFY_DEFAULTUSER_PASS: admin123
