version: '3.8'

services:
  Raneto:
    image: linuxserver/raneto:latest
    container_name: Raneto
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    volumes:
      - /volume1/docker/raneto/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
