version: '3.8'

services:
  Librewolf:
    image: linuxserver/librewolf:latest
    container_name: Librewolf
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/librewolf/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      LIBREWOLF_CLI: "https://www.linuxserver.io/"
