version: '3.8'

services:
  Calligra:
    image: linuxserver/calligra:latest
    container_name: Calligra
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/calligra/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
