version: '3.8'

services:
  libreddit:
    image: libreddit/libreddit:armv7
    container_name: libreddit
    restart: unless-stopped
    ports:
      - "8088:8080/tcp"
    volumes:
      - /portainer/Files/AppData/Config/libreddit:/config
