version: '3.8'

services:
  Phpmyadmin:
    image: linuxserver/phpmyadmin:latest
    container_name: Phpmyadmin
    restart: unless-stopped
    ports:
      - "80:80/tcp"
    volumes:
      - /volume1/docker/phpmyadmin/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: "https://phpmyadmin.example.com"
