version: '3.8'

services:
  Peppermint:
    image: pepperlabs/peppermint:latest
    container_name: Peppermint
    restart: unless-stopped
    ports:
      - "5001:5001/tcp"
    volumes:
      - /srv/dev-disk-by-label-media/Files/AppData/Config/peppermint:/data
    environment:
      PUID: 1000
      PGID: 100
      PORT: 5001
      DB_USERNAME: peppermint
      DB_PASSWORD: 1234
      DB_HOST: postgres
