version: '3.8'

services:
  dashmachine:
    image: rmountjoy/dashmachine:latest
    container_name: dashmachine
    restart: unless-stopped
    ports:
      - "5000:5000/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Dashmachine:/dashmachine/dashmachine/user_data
