version: '3.8'

services:
  baserow:
    image: baserow/baserow:1.22.3
    container_name: baserow
    restart: unless-stopped
    ports:
      - "80/tcp"
    volumes:
      - /opt/mediadepot/apps/baserow:/baserow/data
    environment:
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL}
    labels:
      traefik.enable: "true"
      traefik.http.services.baserow.loadbalancer.server.port: "80"
      traefik.http.routers.baserow.entrypoints: "websecure"
      traefik.http.routers.baserow.tls.certresolver: "mydnschallenge"
