version: '3.8'

services:
  Zotero:
    image: linuxserver/zotero:latest
    container_name: Zotero
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/zotero/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
