version: '3.8'

services:
  logzio-logs-collector:
    image: logzio/docker-collector-logs
    container_name: logzio-logs-collector
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    environment:
      LOGZIO_TOKEN: REPLACE-LOGZIO-TOKEN-HERE
      LOGZIO_URL: "listener.logz.io:5015"
