version: '3.8'

services:
  Lollypop:
    image: linuxserver/lollypop:latest
    container_name: Lollypop
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/lollypop/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
