version: '3.8'

services:
  trilium:
    image: zadam/trilium:latest
    container_name: trilium
    restart: unless-stopped
    ports:
      - "3388:8080/tcp"
    volumes:
      - /portainer/Files/AppData/Config/trilium-data:/home/node/trilium-data
    environment:
      TRILIUM_DATA_DIR: /home/node/trilium-data
      PORT: ${PORT}
