version: '3.8'

services:
  Vscodium:
    image: linuxserver/vscodium:latest
    container_name: Vscodium
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/vscodium/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
