version: '3.8'

services:
  Pwndrop:
    image: linuxserver/pwndrop:latest
    container_name: Pwndrop
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - /volume1/docker/pwndrop/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      SECRET_PATH: /pwndrop
