version: '3.8'

services:
  pihole DoH/DoT:
    image: oijkn/pihole-doh-dot:latest
    container_name: pihole DoH/DoT
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "1010:80/tcp"
      - "4443:443/tcp"
    volumes:
      - /portainer/Files/AppData/Config/PiHole_DoH-DoT:/etc/pihole
      - /portainer/Files/AppData/Config/PiHole_DoH-DoT/DNS:/etc/dnsmasq.d
