version: '3.8'

services:
  Remmina:
    image: linuxserver/remmina:latest
    container_name: Remmina
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/remmina/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
