version: '3.8'

services:
  wg-easy:
    image: undefined
    container_name: wg-easy
    restart: unless-stopped
    environment:
      WG_HOST: example.domain.com
      PASSWORD: ENTER AN ADMIN PASSWORD
      WG_PORT: 51820
      WG_DEFAULT_DNS: 1.1.1.1
      WG_DEFAULT_ADDRESS: 10.8.0.x
      WG_ALLOWED_IPS: "0.0.0.0/0, ::/0"
