version: '3.8'

services:
  Xbackbone:
    image: linuxserver/xbackbone:latest
    container_name: Xbackbone
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /volume1/docker/xbackbone/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
