version: '3.8'

services:
  qflood:
    image: hotio/qflood:latest
    container_name: qflood
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "8080:8080/tcp"
    volumes:
      - /portainer/Files/AppData/Config/qFlood:/config
      - /portainer/Downloads:/app/qBittorrent/downloads
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: America/New_York
      FLOOD_AUTH: false
