version: '3.8'

services:
  eufy-security-ws:
    image: bropat/eufy-security-ws:latest
    container_name: eufy-security-ws
    restart: unless-stopped
    ports:
      - "3993:3000/tcp"
    volumes:
      - /portainer/Files/AppData/Config/eufy-security-ws:/data
    environment:
      USERNAME: InputUSER-email
      PASSWORD: InputPWD
