version: '3.8'

services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    ports:
      - "9091:9091/tcp"
      - "51413:51413/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Transmission:/config
      - /portainer/Files/Downloads:/downloads
      - undefined:/watch
    environment:
      PUID: 1000
      PGID: 100
