version: '3.8'

services:
  logzio-metrics-collector:
    image: logzio/docker-collector-metrics
    container_name: logzio-metrics-collector
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup
      - /proc:/hostfs/proc
      - /:/hostfs
    environment:
      LOGZIO_TOKEN: REPLACE-LOGZIO-TOKEN-HERE
      LOGZIO_MODULES: system,docker
