version: '3.8'

services:
  rustdesk:
    image: rustdesk/rustdesk-server-s6:latest
    container_name: rustdesk
    restart: unless-stopped
    ports:
      - "21115:21115/tcp"
      - "21116:21116/tcp"
      - "21116:21116/udp"
      - "21117:21117/tcp"
      - "21118:21118/tcp"
      - "21119:21119/tcp"
    volumes:
      - /portainer/Files/AppData/Config/rustdesk:/data
    environment:
      RELAY: "rustdesk.example.com:21117"
      ENCRYPTED_ONLY: 1
