version: '3.8'

services:
  netbootxyz:
    image: linuxserver/netbootxyz:latest
    container_name: netbootxyz
    restart: unless-stopped
    ports:
      - "3000/tcp"
      - "69/udp"
    volumes:
      - /opt/mediadepot/apps/netbootxyz:/config
      - /media/storage/software/netbootxyz:/assets
      - /etc/localtime:/etc/localtime
    environment:
      PGID: 15000
      PUID: 15000
    labels:
      traefik.enable: "true"
      traefik.http.services.netbootxyz.loadbalancer.server.port: "3000"
      traefik.http.routers.netbootxyz.entrypoints: "websecure"
      traefik.http.routers.netbootxyz.tls.certresolver: "mydnschallenge"
