version: '3.8'

services:
  Adguardhome-sync:
    image: linuxserver/adguardhome-sync:latest
    container_name: Adguardhome-sync
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - /volume1/docker/adguardhome-sync/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      CONFIGFILE: /config/adguardhome-sync.yaml
