version: '3.8'

services:
  tiddlywiki:
    image: mazzolino/tiddlywiki:latest
    container_name: tiddlywiki
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - /portainer/Files/AppData/Config/TiddlyWiki:/var/lib/tiddlywiki
