version: '3.8'

services:
  transmission-openvpn-latest:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn-latest
    restart: unless-stopped
    ports:
      - "9091:9091/tcp"
    volumes:
      - /portainer/Files/AppData/Config/transmission-openvpn:/config
      - /portainer/Downloads:/data
      - /etc/localtime:/etc/localtime
    environment:
      PUID: 1000
      PGID: 1000
      OPENVPN_PROVIDER: MULLVAD
      OPENVPN_CONFIG: ${OPENVPN_CONFIG}
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      LOCAL_NETWORK: 192.168.0.0/24
      TRANSMISSION_WATCH_DIR_ENABLED: true
