version: '3.8'

services:
  sickgear:
    image: linuxserver/sickgear:latest
    container_name: sickgear
    restart: unless-stopped
    ports:
      - "8081:8081/tcp"
    volumes:
      - /portainer/Files/AppData/Config/SickGear:/config
      - /portainer/TV:/tv
      - /portainer/Downloads:/downloads
    environment:
      PUID: 1000
      PGID: 100
