version: '3.8'

services:
  Rdesktop:
    image: linuxserver/rdesktop:latest
    container_name: Rdesktop
    restart: unless-stopped
    ports:
      - "3389:3389/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/rdesktop/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
