version: '3.8'

services:
  klipper-mainsail-moonraker:
    image: undefined
    container_name: klipper-mainsail-moonraker
    restart: unless-stopped
    environment:
      3D_PRINTER_DEVICE: /dev/ttymxc3
