version: '3.8'

services:
  Spotube:
    image: linuxserver/spotube:latest
    container_name: Spotube
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/spotube/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
