version: '3.8'

services:
  Habridge:
    image: linuxserver/habridge:latest
    container_name: Habridge
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
      - "50000:50000/tcp"
    volumes:
      - /volume1/docker/habridge/config:/config
    environment:
      PUID: 1024
      PGID: 100
      SEC_KEY: <Your Key To Encrypt Security Data>
      TZ: Europe/Amsterdam
