version: '3.8'

services:
  Mullvad-browser:
    image: linuxserver/mullvad-browser:latest
    container_name: Mullvad-browser
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    volumes:
      - /volume1/docker/mullvad-browser/config:/config
    environment:
      PUID: 1024
      PGID: 100
      TZ: Europe/Amsterdam
      LOCAL_NET: 192.168.0.0/16
