version: '3.8'

services:
  organizr-v2:
    image: organizrtools/organizr-v2:php-fpm
    container_name: organizr-v2
    restart: unless-stopped
    ports:
      - "80/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Organizr:/config
    environment:
      PUID: 1000
      PGID: 100
