version: '3.8'

services:
  sickrage:
    image: linuxserver/sickrage:latest
    container_name: sickrage
    restart: unless-stopped
    ports:
      - "8081/tcp"
    volumes:
      - /opt/mediadepot/apps/sickrage:/config
      - /media/storage/downloads/tvshows:/downloads
      - /media/storage/tvshows:/tv
      - /media/temp/blackhole/tvshows:/blackhole
    environment:
      PGID: 15000
      PUID: 15000
      TZ: America/Los_Angeles
    labels:
      traefik.enable: "true"
      traefik.http.services.sickrage.loadbalancer.server.port: "8081"
      traefik.http.routers.sickrage.entrypoints: "websecure"
      traefik.http.routers.sickrage.tls.certresolver: "mydnschallenge"
