version: '3.8'

services:
  DaVinci Postgres Server:
    image: postgres:13
    container_name: DaVinci Postgres Server
    restart: unless-stopped
    ports:
      - "5432:5432/tcp"
    volumes:
      - /portainer/Files/AppData/Config/DavinciServer/:/var/lib/postgresql/data
    environment:
      PUID: 1000
      PGID: 1000
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DaVinci
      TZ: America/New_York
