version: '3.8'

services:
  klaxon:
    image: undefined
    container_name: klaxon
    restart: unless-stopped
    environment:
      SMTP_PROVIDER: SENDGRID
      SENDGRID_USERNAME: ${SENDGRID_USERNAME}
      SENDGRID_PASSWORD: ${SENDGRID_PASSWORD}
      ADMIN_EMAILS: ${ADMIN_EMAILS}
