version: '3.8'

services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge:latest
    container_name: protonmail-bridge
    restart: unless-stopped
    ports:
      - "143/tcp"
      - "25/tcp"
    volumes:
      - /portainer/Files/AppData/ProtonMail-Bridge:/root
