version: '3.8'

services:
  Kavita:
    image: kizaing/kavita:latest
    container_name: Kavita
    restart: unless-stopped
    ports:
      - "5000:5000/tcp"
    volumes:
      - undefined:/books
      - undefined:/comics
      - undefined:/manga
      - undefined:/config
    environment:
      PUID: 1000
      PGID: 100
