version: '3.8'

services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
      - "9090:9090/tcp"
    volumes:
      - /portainer/Files/AppData/Config/Sabnzbd:/config
      - /portainer/Downloads:/downloads
      - /portainer/Downloads/incomplete:/incomplete-downloads
    environment:
      PUID: 1000
      PGID: 100
