version: '3.8'

services:
  kodi-headless:
    image: linuxserver/kodi-headless:latest
    container_name: kodi-headless
    restart: unless-stopped
    ports:
      - "8080/tcp"
      - "9777/udp"
    volumes:
      - /portainer/Files/AppData/Config/Kodi:/config
    environment:
      PUID: 1000
      PGID: 100
