version: '3.8'

services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - "9117/tcp"
    volumes:
      - /opt/mediadepot/apps/jackett:/config
      - /media/storage/downloads:/downloads
      - /etc/localtime:/etc/localtime
    environment:
      PGID: 15000
      PUID: 15000
      TZ: America/Los_Angeles
    labels:
      traefik.enable: "true"
      traefik.http.services.jackett.loadbalancer.server.port: "9117"
      traefik.http.routers.jackett.entrypoints: "websecure"
      traefik.http.routers.jackett.tls.certresolver: "mydnschallenge"
