version: '3.8'

services:
  gaps:
    image: housewrecker/gaps:latest
    container_name: gaps
    restart: unless-stopped
    ports:
      - "8484/tcp"
    environment:
      TZ: America/Los_Angeles
    labels:
      traefik.enable: "true"
      traefik.http.services.gaps.loadbalancer.server.port: "8484"
      traefik.http.routers.gaps.entrypoints: "websecure"
      traefik.http.routers.gaps.tls.certresolver: "mydnschallenge"
